---
title: Data Types
author: R package build
date: '2022-02-23'
slug: data-types
categories: []
tags: []
---

# Cat Lovers
```{r}
library(tidyverse)
catlovers <- "https://raw.githubusercontent.com/Lior1430/tidyverse/main/cat-lovers.csv"

cat_lovers <- read_csv(catlovers)
```

## Summarize Data
```{r}
cat_lovers %>%
  summarise(mean_cats = mean(number_of_cats, na.rm = TRUE))
```

```{r}
glimpse(cat_lovers)
```

## Fixing the "Bad" Data
```{r}
cat_lovers %>%
  mutate(
    number_of_cats = case_when(
      name == "Ginger Clark" ~ "2",
      name == "Doug Bass"    ~ "3",
      TRUE                   ~ number_of_cats
      ),
    number_of_cats = as.numeric(number_of_cats)
    ) %>%
  summarise(mean_cats = mean(number_of_cats))
```

# Data Types

## Logical
```{r}
typeof(TRUE)
```

## Character
```{r}
typeof("hello")
```

## Double
```{r}
typeof(1.335)

typeof(7)
```

## Integer
```{r}
typeof(7L)

typeof(1:3)
```

# Concatenation
```{r}
#Creatng a vector
c(1, 2, 3)

c("Hello", "World!")

c(c("hi", "hello"), c("bye", "jello"))
```

# Converting Between Data Types

## Explicit Coersion
```{r}
x <- 1:3
x
typeof(x)
```
```{r}
y <- as.character(x)
y
typeof(y)
```

```{r}
x <- c(TRUE, FALSE)
x
typeof(x)
```
```{r}
y <- as.numeric(x)
y
typeof(y)
```

## Implicit Coersion
```{r}
c(1, "Hello")

c(FALSE, 3L)
```

```{r}
c(1.2, 3L)

c(2L, "two")
```

# Special Values 

## NA's
```{r}
#Not available
x <- c(1, 2, 3, 4, NA)
mean(x)
```
```{r}
mean(x, na.rm = TRUE)
summary(x)
```

```{r}
typeof(NA)
```

## NaN
```{r}
# Not a number
```

## Inf
```{r}
# Positive infinity
```

## -Inf
```{r}
# Negative Infinity
```

