---
title: "Intro to Rmarkdown"
author: "Lior S"
date: "2022-02-16"
slug: intro-to-rmarkdown
categories: []
tags: []
output:
  html_document:
    theme: yeti
    highlight: zenburn
    df_print: paged
    toc: true
    toc_float: true
---

<script src="{{< blogdown/postref >}}index_files/header-attrs/header-attrs.js"></script>


<pre class="r"><code>library(datasets)
data(iris)
#load packages
pkgs &lt;- c(&quot;rstatix&quot;, &quot;emmeans&quot;, &quot;psych&quot;, &quot;tidyr&quot;, &quot;tidyverse&quot;, &quot;psych&quot;, &quot;dplyr&quot;, &quot;ggplot2&quot;, &quot;lm.beta&quot;, &quot;car&quot;, &quot;Hmisc&quot;, &quot;skimr&quot;, &quot;janitor&quot;)
lapply(pkgs, library, character.only = TRUE)</code></pre>
<div id="intro" class="section level1">
<h1>Intro</h1>
<div id="code-chunks" class="section level2">
<h2>Code Chunks</h2>
<pre class="r"><code>#Sum of 2 + 2
2 + 2</code></pre>
<pre><code>## [1] 4</code></pre>
<pre class="r"><code>#Average Sepal Length
mean(iris$Sepal.Length)</code></pre>
<pre><code>## [1] 5.843333</code></pre>
<pre class="r"><code>#Levels of Species
unique(iris$Species)</code></pre>
<pre><code>## [1] setosa     versicolor virginica 
## Levels: setosa versicolor virginica</code></pre>
</div>
<div id="inline-code" class="section level2">
<h2>Inline Code</h2>
<p>Two plus two equals 4
The average Sepal Length is 5.8433333
The three levels of Species are setosa, versicolor, virginica</p>
</div>
</div>
<div id="basics" class="section level1">
<h1>Basics</h1>
<div id="text" class="section level2">
<h2>Text</h2>
<p>Plain Text - hello!<br />
End a line with two spaces to start a new paragraph.<br />
<em>italics</em> and <em>italics</em><br />
<strong>bold</strong> and <strong>bold</strong><br />
<del>strikethrough</del><br />
<a href="www.rstudio.com">link</a></p>
</div>
<div id="headers-level-2" class="section level2">
<h2>Headers (level 2)</h2>
<pre class="r"><code>Make sure to leave a space between the # and your text
# Header 1  
## Header 2  
### Header 3  
#### Header 4  
##### Header 5  
###### Header 6  </code></pre>
</div>
<div id="symbols" class="section level2">
<h2>Symbols</h2>
<p>endash: –<br />
emdash: —<br />
ellipsis: …<br />
inline equation: <span class="math inline">\(A = \pi*r^{2}\)</span></p>
<p>horizontal rule (or slide break):</p>
<hr />
</div>
<div id="formatting" class="section level2">
<h2>Formatting</h2>
<blockquote>
<p>block quote</p>
</blockquote>
<ul>
<li>unordered list</li>
<li>item 2
<ul>
<li>sub-item 1 (one tab)<br />
</li>
<li>sub-item 2 (one tab)</li>
</ul></li>
</ul>
<ol style="list-style-type: decimal">
<li>ordered list</li>
<li>item 2
<ul>
<li>sub-item 1 (two tabs)<br />
</li>
<li>sub-item 2 (two tabs)</li>
</ul></li>
</ol>
<table>
<thead>
<tr class="header">
<th>First Header</th>
<th>Second Header</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>5.8433333</td>
<td>Cell 2</td>
</tr>
<tr class="even">
<td>Cell 3</td>
<td>Cell 4</td>
</tr>
</tbody>
</table>
</div>
<div id="date" class="section level2">
<h2>Date</h2>
<pre class="r"><code>#Add this to date ao that today&#39;s date is printed whenever dos is knitted
title: &quot;Intro to Rmarkdown&quot;
author: &quot;Lior S&quot;
date: &quot;`r Sys.Date()`&quot;</code></pre>
</div>
</div>
<div id="code-specifications" class="section level1">
<h1>Code Specifications</h1>
<div id="display-code" class="section level2">
<h2>Display Code</h2>
<pre><code>##   Sepal.Length    Sepal.Width     Petal.Length    Petal.Width   
##  Min.   :4.300   Min.   :2.000   Min.   :1.000   Min.   :0.100  
##  1st Qu.:5.100   1st Qu.:2.800   1st Qu.:1.600   1st Qu.:0.300  
##  Median :5.800   Median :3.000   Median :4.350   Median :1.300  
##  Mean   :5.843   Mean   :3.057   Mean   :3.758   Mean   :1.199  
##  3rd Qu.:6.400   3rd Qu.:3.300   3rd Qu.:5.100   3rd Qu.:1.800  
##  Max.   :7.900   Max.   :4.400   Max.   :6.900   Max.   :2.500  
##        Species  
##  setosa    :50  
##  versicolor:50  
##  virginica :50  
##                 
##                 
## </code></pre>
</div>
<div id="display-warnings" class="section level2">
<h2>Display Warnings</h2>
<pre class="r"><code>warning = TRUE: whether to display warnings</code></pre>
<div id="with-warning" class="section level3">
<h3>With Warning</h3>
<pre class="r"><code>data &lt;- data.frame(x = 1:5, y = 1:5)
ggp &lt;- ggplot(data, aes(x, y)) +
  geom_point()

ggp +
  scale_x_continuous(limits = c(2, 5))</code></pre>
<pre><code>## Warning: Removed 1 rows containing missing values (geom_point).</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-10-1.png" width="672" /></p>
</div>
<div id="without-warning" class="section level3">
<h3>Without Warning</h3>
<pre class="r"><code>ggp +
  scale_x_continuous(limits = c(2,5))</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-11-1.png" width="672" /></p>
</div>
</div>
<div id="display-errors" class="section level2">
<h2>Display Errors</h2>
<pre class="r"><code>error = FALSE: Whether to display error messages
Deafault is error = TRUE</code></pre>
</div>
<div id="display-output" class="section level2">
<h2>Display Output</h2>
<pre class="r"><code>Default results = FALSE</code></pre>
<div id="output-included" class="section level3">
<h3>Output Included</h3>
<pre class="r"><code>summary(iris)</code></pre>
<pre><code>##   Sepal.Length    Sepal.Width     Petal.Length    Petal.Width   
##  Min.   :4.300   Min.   :2.000   Min.   :1.000   Min.   :0.100  
##  1st Qu.:5.100   1st Qu.:2.800   1st Qu.:1.600   1st Qu.:0.300  
##  Median :5.800   Median :3.000   Median :4.350   Median :1.300  
##  Mean   :5.843   Mean   :3.057   Mean   :3.758   Mean   :1.199  
##  3rd Qu.:6.400   3rd Qu.:3.300   3rd Qu.:5.100   3rd Qu.:1.800  
##  Max.   :7.900   Max.   :4.400   Max.   :6.900   Max.   :2.500  
##        Species  
##  setosa    :50  
##  versicolor:50  
##  virginica :50  
##                 
##                 
## </code></pre>
</div>
<div id="output-not-included" class="section level3">
<h3>Output Not Included</h3>
<pre class="r"><code>summary(iris)</code></pre>
</div>
</div>
<div id="display-messages" class="section level2">
<h2>Display Messages</h2>
<pre class="r"><code>Default message = TRUE</code></pre>
<div id="messages-not-included" class="section level3">
<h3>Messages Not Included</h3>
<pre class="r"><code>#load packages
pkgs &lt;- c(&quot;rstatix&quot;, &quot;emmeans&quot;, &quot;psych&quot;, &quot;tidyr&quot;, &quot;tidyverse&quot;, &quot;psych&quot;, &quot;dplyr&quot;, &quot;ggplot2&quot;, &quot;lm.beta&quot;, &quot;car&quot;, &quot;Hmisc&quot;, &quot;skimr&quot;, &quot;janitor&quot;)
lapply(pkgs, library, character.only = TRUE)</code></pre>
<pre><code>## [[1]]
##  [1] &quot;janitor&quot;   &quot;skimr&quot;     &quot;Hmisc&quot;     &quot;Formula&quot;   &quot;survival&quot;  &quot;lattice&quot;  
##  [7] &quot;car&quot;       &quot;carData&quot;   &quot;lm.beta&quot;   &quot;forcats&quot;   &quot;stringr&quot;   &quot;dplyr&quot;    
## [13] &quot;purrr&quot;     &quot;readr&quot;     &quot;tibble&quot;    &quot;ggplot2&quot;   &quot;tidyverse&quot; &quot;tidyr&quot;    
## [19] &quot;psych&quot;     &quot;emmeans&quot;   &quot;rstatix&quot;   &quot;stats&quot;     &quot;graphics&quot;  &quot;grDevices&quot;
## [25] &quot;utils&quot;     &quot;datasets&quot;  &quot;methods&quot;   &quot;base&quot;     
## 
## [[2]]
##  [1] &quot;janitor&quot;   &quot;skimr&quot;     &quot;Hmisc&quot;     &quot;Formula&quot;   &quot;survival&quot;  &quot;lattice&quot;  
##  [7] &quot;car&quot;       &quot;carData&quot;   &quot;lm.beta&quot;   &quot;forcats&quot;   &quot;stringr&quot;   &quot;dplyr&quot;    
## [13] &quot;purrr&quot;     &quot;readr&quot;     &quot;tibble&quot;    &quot;ggplot2&quot;   &quot;tidyverse&quot; &quot;tidyr&quot;    
## [19] &quot;psych&quot;     &quot;emmeans&quot;   &quot;rstatix&quot;   &quot;stats&quot;     &quot;graphics&quot;  &quot;grDevices&quot;
## [25] &quot;utils&quot;     &quot;datasets&quot;  &quot;methods&quot;   &quot;base&quot;     
## 
## [[3]]
##  [1] &quot;janitor&quot;   &quot;skimr&quot;     &quot;Hmisc&quot;     &quot;Formula&quot;   &quot;survival&quot;  &quot;lattice&quot;  
##  [7] &quot;car&quot;       &quot;carData&quot;   &quot;lm.beta&quot;   &quot;forcats&quot;   &quot;stringr&quot;   &quot;dplyr&quot;    
## [13] &quot;purrr&quot;     &quot;readr&quot;     &quot;tibble&quot;    &quot;ggplot2&quot;   &quot;tidyverse&quot; &quot;tidyr&quot;    
## [19] &quot;psych&quot;     &quot;emmeans&quot;   &quot;rstatix&quot;   &quot;stats&quot;     &quot;graphics&quot;  &quot;grDevices&quot;
## [25] &quot;utils&quot;     &quot;datasets&quot;  &quot;methods&quot;   &quot;base&quot;     
## 
## [[4]]
##  [1] &quot;janitor&quot;   &quot;skimr&quot;     &quot;Hmisc&quot;     &quot;Formula&quot;   &quot;survival&quot;  &quot;lattice&quot;  
##  [7] &quot;car&quot;       &quot;carData&quot;   &quot;lm.beta&quot;   &quot;forcats&quot;   &quot;stringr&quot;   &quot;dplyr&quot;    
## [13] &quot;purrr&quot;     &quot;readr&quot;     &quot;tibble&quot;    &quot;ggplot2&quot;   &quot;tidyverse&quot; &quot;tidyr&quot;    
## [19] &quot;psych&quot;     &quot;emmeans&quot;   &quot;rstatix&quot;   &quot;stats&quot;     &quot;graphics&quot;  &quot;grDevices&quot;
## [25] &quot;utils&quot;     &quot;datasets&quot;  &quot;methods&quot;   &quot;base&quot;     
## 
## [[5]]
##  [1] &quot;janitor&quot;   &quot;skimr&quot;     &quot;Hmisc&quot;     &quot;Formula&quot;   &quot;survival&quot;  &quot;lattice&quot;  
##  [7] &quot;car&quot;       &quot;carData&quot;   &quot;lm.beta&quot;   &quot;forcats&quot;   &quot;stringr&quot;   &quot;dplyr&quot;    
## [13] &quot;purrr&quot;     &quot;readr&quot;     &quot;tibble&quot;    &quot;ggplot2&quot;   &quot;tidyverse&quot; &quot;tidyr&quot;    
## [19] &quot;psych&quot;     &quot;emmeans&quot;   &quot;rstatix&quot;   &quot;stats&quot;     &quot;graphics&quot;  &quot;grDevices&quot;
## [25] &quot;utils&quot;     &quot;datasets&quot;  &quot;methods&quot;   &quot;base&quot;     
## 
## [[6]]
##  [1] &quot;janitor&quot;   &quot;skimr&quot;     &quot;Hmisc&quot;     &quot;Formula&quot;   &quot;survival&quot;  &quot;lattice&quot;  
##  [7] &quot;car&quot;       &quot;carData&quot;   &quot;lm.beta&quot;   &quot;forcats&quot;   &quot;stringr&quot;   &quot;dplyr&quot;    
## [13] &quot;purrr&quot;     &quot;readr&quot;     &quot;tibble&quot;    &quot;ggplot2&quot;   &quot;tidyverse&quot; &quot;tidyr&quot;    
## [19] &quot;psych&quot;     &quot;emmeans&quot;   &quot;rstatix&quot;   &quot;stats&quot;     &quot;graphics&quot;  &quot;grDevices&quot;
## [25] &quot;utils&quot;     &quot;datasets&quot;  &quot;methods&quot;   &quot;base&quot;     
## 
## [[7]]
##  [1] &quot;janitor&quot;   &quot;skimr&quot;     &quot;Hmisc&quot;     &quot;Formula&quot;   &quot;survival&quot;  &quot;lattice&quot;  
##  [7] &quot;car&quot;       &quot;carData&quot;   &quot;lm.beta&quot;   &quot;forcats&quot;   &quot;stringr&quot;   &quot;dplyr&quot;    
## [13] &quot;purrr&quot;     &quot;readr&quot;     &quot;tibble&quot;    &quot;ggplot2&quot;   &quot;tidyverse&quot; &quot;tidyr&quot;    
## [19] &quot;psych&quot;     &quot;emmeans&quot;   &quot;rstatix&quot;   &quot;stats&quot;     &quot;graphics&quot;  &quot;grDevices&quot;
## [25] &quot;utils&quot;     &quot;datasets&quot;  &quot;methods&quot;   &quot;base&quot;     
## 
## [[8]]
##  [1] &quot;janitor&quot;   &quot;skimr&quot;     &quot;Hmisc&quot;     &quot;Formula&quot;   &quot;survival&quot;  &quot;lattice&quot;  
##  [7] &quot;car&quot;       &quot;carData&quot;   &quot;lm.beta&quot;   &quot;forcats&quot;   &quot;stringr&quot;   &quot;dplyr&quot;    
## [13] &quot;purrr&quot;     &quot;readr&quot;     &quot;tibble&quot;    &quot;ggplot2&quot;   &quot;tidyverse&quot; &quot;tidyr&quot;    
## [19] &quot;psych&quot;     &quot;emmeans&quot;   &quot;rstatix&quot;   &quot;stats&quot;     &quot;graphics&quot;  &quot;grDevices&quot;
## [25] &quot;utils&quot;     &quot;datasets&quot;  &quot;methods&quot;   &quot;base&quot;     
## 
## [[9]]
##  [1] &quot;janitor&quot;   &quot;skimr&quot;     &quot;Hmisc&quot;     &quot;Formula&quot;   &quot;survival&quot;  &quot;lattice&quot;  
##  [7] &quot;car&quot;       &quot;carData&quot;   &quot;lm.beta&quot;   &quot;forcats&quot;   &quot;stringr&quot;   &quot;dplyr&quot;    
## [13] &quot;purrr&quot;     &quot;readr&quot;     &quot;tibble&quot;    &quot;ggplot2&quot;   &quot;tidyverse&quot; &quot;tidyr&quot;    
## [19] &quot;psych&quot;     &quot;emmeans&quot;   &quot;rstatix&quot;   &quot;stats&quot;     &quot;graphics&quot;  &quot;grDevices&quot;
## [25] &quot;utils&quot;     &quot;datasets&quot;  &quot;methods&quot;   &quot;base&quot;     
## 
## [[10]]
##  [1] &quot;janitor&quot;   &quot;skimr&quot;     &quot;Hmisc&quot;     &quot;Formula&quot;   &quot;survival&quot;  &quot;lattice&quot;  
##  [7] &quot;car&quot;       &quot;carData&quot;   &quot;lm.beta&quot;   &quot;forcats&quot;   &quot;stringr&quot;   &quot;dplyr&quot;    
## [13] &quot;purrr&quot;     &quot;readr&quot;     &quot;tibble&quot;    &quot;ggplot2&quot;   &quot;tidyverse&quot; &quot;tidyr&quot;    
## [19] &quot;psych&quot;     &quot;emmeans&quot;   &quot;rstatix&quot;   &quot;stats&quot;     &quot;graphics&quot;  &quot;grDevices&quot;
## [25] &quot;utils&quot;     &quot;datasets&quot;  &quot;methods&quot;   &quot;base&quot;     
## 
## [[11]]
##  [1] &quot;janitor&quot;   &quot;skimr&quot;     &quot;Hmisc&quot;     &quot;Formula&quot;   &quot;survival&quot;  &quot;lattice&quot;  
##  [7] &quot;car&quot;       &quot;carData&quot;   &quot;lm.beta&quot;   &quot;forcats&quot;   &quot;stringr&quot;   &quot;dplyr&quot;    
## [13] &quot;purrr&quot;     &quot;readr&quot;     &quot;tibble&quot;    &quot;ggplot2&quot;   &quot;tidyverse&quot; &quot;tidyr&quot;    
## [19] &quot;psych&quot;     &quot;emmeans&quot;   &quot;rstatix&quot;   &quot;stats&quot;     &quot;graphics&quot;  &quot;grDevices&quot;
## [25] &quot;utils&quot;     &quot;datasets&quot;  &quot;methods&quot;   &quot;base&quot;     
## 
## [[12]]
##  [1] &quot;janitor&quot;   &quot;skimr&quot;     &quot;Hmisc&quot;     &quot;Formula&quot;   &quot;survival&quot;  &quot;lattice&quot;  
##  [7] &quot;car&quot;       &quot;carData&quot;   &quot;lm.beta&quot;   &quot;forcats&quot;   &quot;stringr&quot;   &quot;dplyr&quot;    
## [13] &quot;purrr&quot;     &quot;readr&quot;     &quot;tibble&quot;    &quot;ggplot2&quot;   &quot;tidyverse&quot; &quot;tidyr&quot;    
## [19] &quot;psych&quot;     &quot;emmeans&quot;   &quot;rstatix&quot;   &quot;stats&quot;     &quot;graphics&quot;  &quot;grDevices&quot;
## [25] &quot;utils&quot;     &quot;datasets&quot;  &quot;methods&quot;   &quot;base&quot;     
## 
## [[13]]
##  [1] &quot;janitor&quot;   &quot;skimr&quot;     &quot;Hmisc&quot;     &quot;Formula&quot;   &quot;survival&quot;  &quot;lattice&quot;  
##  [7] &quot;car&quot;       &quot;carData&quot;   &quot;lm.beta&quot;   &quot;forcats&quot;   &quot;stringr&quot;   &quot;dplyr&quot;    
## [13] &quot;purrr&quot;     &quot;readr&quot;     &quot;tibble&quot;    &quot;ggplot2&quot;   &quot;tidyverse&quot; &quot;tidyr&quot;    
## [19] &quot;psych&quot;     &quot;emmeans&quot;   &quot;rstatix&quot;   &quot;stats&quot;     &quot;graphics&quot;  &quot;grDevices&quot;
## [25] &quot;utils&quot;     &quot;datasets&quot;  &quot;methods&quot;   &quot;base&quot;</code></pre>
</div>
</div>
<div id="other-specifications" class="section level2">
<h2>Other Specifications</h2>
<pre class="r"><code>eval = TRUE: Whether to evaluate the code and include its results
tidy = FALSE: Whether to reformat code in a tidy way when displaying it
fig.width = 7: Width in inches for plots created in chunk
fig.height = 7: Height in inches for plots created in chunk</code></pre>
</div>
<div id="global-specifications" class="section level2">
<h2>Global Specifications</h2>
</div>
<div id="bold-code" class="section level2">
<h2>Bold Code</h2>
<pre class="r"><code>### &lt;b&gt;
x &lt;- 10
y &lt;- x * 2</code></pre>
</div>
</div>
<div id="table-of-contents" class="section level1">
<h1>Table of Contents</h1>
<div id="basic-toc" class="section level2">
<h2>Basic TOC</h2>
<pre class="r"><code>title: &quot;Intro to Rmarkdown&quot;
author: &quot;Lior S&quot;
date: &quot;2/16/2022&quot;
output:
  html_document
  toc: true
  toc_depth: 2</code></pre>
</div>
<div id="floating-toc" class="section level2">
<h2>Floating TOC</h2>
<pre class="r"><code>title: &quot;Intro to Rmarkdown&quot;
author: &quot;Lior S&quot;
date: &quot;2/16/2022&quot;
output:
  html_document
  toc: true
  toc_float: true
  collapsed: true #If TOC appears with only top-level headers
  smooth_scroll: true #Whether page scrolls are animated with mouse clicks
  toc_depth: 3</code></pre>
</div>
</div>
<div id="tabs" class="section level1 tabset">
<h1>Tabs</h1>
<ul>
<li>You can make it so that all subheadings are tabbed by using the {.tabset} after heading tite</li>
</ul>
<div id="study-1" class="section level2">
<h2>Study 1</h2>
<pre class="r"><code>e.g. = study 1 graph</code></pre>
</div>
<div id="study-2" class="section level2">
<h2>Study 2</h2>
<pre class="r"><code>e.g. = study 2 graph</code></pre>
</div>
</div>
<div id="appearance" class="section level1">
<h1>Appearance</h1>
<div id="themes" class="section level2">
<h2>Themes</h2>
<div id="built-in-themes" class="section level3">
<h3>Built-In Themes</h3>
<ul>
<li>See here for a gallery of the different
<a href="https://www.datadreaming.org/post/r-markdown-theme-gallery/">themes</a></li>
</ul>
<pre class="r"><code>#Specify this in the beginning of the doc (we are using the yeti theme)
theme: Specifies theme to use from the Bootswatch theme library

Specify: default, cerulean, journal, flatly, darkly, readable, spacelab, united, cosmo, lumen, paper, sandstone, simplex. and yeti (use null for no theme)</code></pre>
</div>
<div id="downoadable-themes" class="section level3">
<h3>Downoadable Themes</h3>
<p>*Once you download/install this package you can use it when you create a new markdown.</p>
<pre class="r"><code>#There are a couple downloadable themes, and this is one
#This won&#39;t run automatically if you knit this scrit so you will need to run each line to install and load the package.
install.packages(&#39;rmdformats&#39;)
library(rmdformats)</code></pre>
</div>
</div>
<div id="highight" class="section level2">
<h2>Highight</h2>
<pre class="r"><code>#Specify this in the beginning of the doc
Hightight: Species syntax highlighting style

Specify: default, tango, payments, kate, monochrome, espresso, zenburn, haddock, breezedark, and textmate (use null for no highlight)</code></pre>
</div>
<div id="smart" class="section level2">
<h2>Smart</h2>
<p>#Specify this in the beginning of the doc
Smart changes: straight quotes to curly quotes, — to em-dashes, – to en-dashes, and … to ellipses</p>
<p>Smart is enabled by default</p>
<div id="data-frame-printing" class="section level3">
<h3>Data Frame Printing</h3>
<pre class="r"><code>#df_print: specifies how data is printed
#df_print = paged, creates a pageable table

output:
  html_document:
    df_print: paged</code></pre>
</div>
</div>
</div>
<div id="figures" class="section level1">
<h1>Figures</h1>
<div id="embed-images" class="section level2">
<h2>Embed Images</h2>
<p>image: <img src="nyu.jpeg" />{width = 50%}</p>
</div>
<div id="creating-images" class="section level2">
<h2>Creating Images</h2>
<pre class="r"><code>#Specify this at the beginning of the doc
fig.width: 7
fig.height: 7
fig.caption: true #Adds captions to figures
dev: png #Specifies types of images figures will be</code></pre>
</div>
</div>
<div id="advanced-inline-code" class="section level1">
<h1>Advanced Inline Code</h1>
<pre class="r"><code>#Run anova
model &lt;- aov(Sepal.Length ~ Species, data = iris)
summary(model)</code></pre>
<pre><code>##              Df Sum Sq Mean Sq F value Pr(&gt;F)    
## Species       2  63.21  31.606   119.3 &lt;2e-16 ***
## Residuals   147  38.96   0.265                   
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<pre class="r"><code>#Create clean tibble from output using broom package
library(broom)
modelmatrix &lt;- broom::tidy(model)

#Round to 3 decimals for clean output
modelmatrix$statistic &lt;- sprintf(modelmatrix$statistic, fmt = &#39;%#.3f&#39;)
modelmatrix$p.value &lt;- sprintf(modelmatrix$p.value, fmt = &#39;%#.3f&#39;)

modelmatrix</code></pre>
<pre><code>## # A tibble: 2 × 6
##   term         df sumsq meansq statistic p.value
##   &lt;chr&gt;     &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;chr&gt;     &lt;chr&gt;  
## 1 Species       2  63.2 31.6   119.265   0.000  
## 2 Residuals   147  39.0  0.265 NA        NA</code></pre>
<blockquote>
<p>There is a significant main effect of Species on Sepal Length, <em>F</em>(2, 147) = (119.265, <em>p</em> = 0.000</p>
</blockquote>
</div>
<div id="notes" class="section level1">
<h1>Notes</h1>
<blockquote>
<ol style="list-style-type: decimal">
<li>Using ~ in your paths doesn’t work with rmd</li>
<li>Be mindful of the pathways/working directory you are using</li>
<li>Make sure you are knitting the right type of doc (if it is html, knit is as html)</li>
<li>Make sure you are using ` (backquote) not ’ (apostrophe)</li>
<li>Make sure you are capitalizing all letters in the {r} code specifications</li>
</ol>
<ul>
<li>You want {r, eval = FALSE}</li>
<li>You don’t want {r, eval = False}</li>
</ul>
<ol start="6" style="list-style-type: decimal">
<li>The knitted doc is different depending on which type of rmarkdown script you use (html vs. pdf, etc.)</li>
</ol>
<ul>
<li>For example, floating TOC looks weird in PDF</li>
</ul>
<ol start="7" style="list-style-type: decimal">
<li>Don’t forget to add a space between the # and the header</li>
<li>To hide library loadings use both results = FALSE and message = FALSE</li>
</ol>
</blockquote>
</div>
