---
title: "Palmer Penguins"
author: "R package build"
date: '2022-02-09'
slug: palmer-penguins
categories: []
tags:
- Penguin
- GGPLOT2
---

# Palmer Penguins

Measurements for penguin species, island in **Palmer Archipeago**, size (flipper length, body mass, bill dimensions), and sex.

## Call Libraries
```{r Libraries, message=TRUE, warning=FALSE, paged.print=FALSE}
library(tidyverse)
library(palmerpenguins)
```

## Describing the Data
```{r}
glimpse(penguins)
```

## Scatter Plot
```{r warning = FALSE}
ggplot(data = penguins, 
       mapping = aes(x = bill_depth_mm, y = bill_length_mm,
                     colour = species)) +
  geom_point() +
  labs(title = "Bill depth and length",
       subtitle = "Dimensions for Adelie, Chinstrap, and Gentoo Penguins",
       x = "Bill depth (mm)", y = "Bill length (mm)",
       colour = "Species", caption = "Source: Palmer Station LTR / palmerspenguins package") + scale_colour_viridis_d()
```

## Scatter Plot Enhanced
```{r warning = FALSE}
ggplot(penguins,
       aes(x = bill_depth_mm, 
           y = bill_length_mm,
           colour = species,
           shape = species,
           size = body_mass_g,
           alpha = flipper_length_mm)) +
  geom_point() +
  scale_colour_viridis_d()
```

## Scatter Plot with Facet Grid
```{r}
ggplot(penguins, aes(x = bill_depth_mm, y = bill_length_mm)) + 
  geom_point() +
  facet_grid(species ~ island)
```

